[package]
authors = ["Ryan"]
edition = "2018"
name = "resources"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.1"
log = "0.4.14"
serde_json = "1.0.70"
simple_logger = "1.13.0"
tokio = {version = "1.14.0", features = ["full"]}

[[bin]]
name = "bootstrap"
path = "src/main.rs"
