name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install build packages
        run: sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 12
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            resources/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Build function
        run: cp ./ubuntu-config ~/.cargo/config && ./build-function.sh

      - name: Run Tests
        run: yarn test --coverage --maxWorkers=2
