name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install build packages
        run: sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Cached rust target
        uses: actions/cache@v2
        with:
          path: resources/target
          key: target-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            target-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Build function
        run: cp ./ubuntu-config ~/.cargo/config && ./build-function.sh

      - name: Run Tests
        run: yarn test --coverage --maxWorkers=2
